[metadata]
service_namespace = "Strategy₿"
process_name = "M8MulPrc"
plugin_name = "m8mulprc"
description = "Strategy₿ Multi-Process Controller monitoring"
author = "laplaque/instana_plugins Contributors"

[monitoring]
default_interval = 60
process_patterns = ["M8MulPrc", "m8mulprc"]
metric_types = ["cpu", "memory", "io", "network"]
supports_discovery = true
log_process_details = true

[installation]
systemd_service_name = "instana-m8mulprc-monitor"
service_description = "Instana Strategy₿ M8MulPrc Monitor"
default_base_dir = "/opt/instana_plugins"
requires_root = false
creates_logs_directory = true

[dependencies]
python_min_version = "3.6"
additional_packages = []

[otel_config]
default_agent_host = "localhost"
default_agent_port = 4317
service_name_template = "{service_namespace}.{process_name}"
