name: Auto Tag PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  call-reusable-workflow:
    if: github.event.pull_request.merged == true
    uses: laplaque/.github/.github/workflows/reusable-auto-tag.yml@master
    secrets: inherit
