name: Validate Tag Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Validate tag is newer version
        run: |
          # Get the current tag
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo "Current tag: $CURRENT_TAG"
          
          # Remove 'v' prefix for version comparison
          CURRENT_VERSION=${CURRENT_TAG#v}
          
          # Get all previous tags, sort by version, and get the latest
          PREVIOUS_TAGS=$(git tag -l "v*.*.*" | grep -v $CURRENT_TAG || echo "")
          
          if [ -z "$PREVIOUS_TAGS" ]; then
            echo "No previous tags found. This is the first tag."
            exit 0
          fi
          
          PREVIOUS_TAG=$(echo "$PREVIOUS_TAGS" | sort -V | tail -n 1)
          echo "Previous tag: $PREVIOUS_TAG"
          PREVIOUS_VERSION=${PREVIOUS_TAG#v}
          
          # Compare versions
          if [ "$(printf '%s\n' "$PREVIOUS_VERSION" "$CURRENT_VERSION" | sort -V | head -n1)" = "$CURRENT_VERSION" ]; then
            if [ "$PREVIOUS_VERSION" = "$CURRENT_VERSION" ]; then
              echo "Error: Current tag ($CURRENT_TAG) is the same as previous tag ($PREVIOUS_TAG)"
            else
              echo "Error: Current tag ($CURRENT_TAG) is lower than previous tag ($PREVIOUS_TAG)"
            fi
            exit 1
          else
            echo "Tag validation passed: $CURRENT_TAG is newer than $PREVIOUS_TAG"
          fi
